global:
  scrape_interval: 5s

# ✅ Alert Rules Load
rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Node Exporter
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # cAdvisor
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

# ✅ Alertmanager Connection
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

